### ISSUE TITLE
Not receiving any events at all from some geographical areas

### ISSUE THREAD

**Issue by Lelelo1** [beeradmoore/Xam.Plugin.Mixpanel.iOS#4]
First all, thank you for these bindings.

I am experiencing users in geographical areas outside US and Europe to not have their events received in Mixpanel. Among the number of app installers, only 40% of them send any events. All of these are American or European, none have been Asian.
I'ts a to big percentage that don't send events. I would find it hard to believe that such a big portion of people don't start an app they have installed? 
Any tips on how I can dig into this further, and troubleshoot what could be the issue behind it?

The app is iOS only
It has had 48 downloads so far

I will also create a thread at Mixpanel

**Comment by beeradmoore** [comment]
Hey @Lelelo1 , the only thing that comes to mind is that those users have disabled tracking. Unsure if iOS 14.5 "ask not to track" does that. If not certain networks (eg with Pi.hole installed) can block access to trackers.

I haven't noticed any drop off in my production apps.

Other than that you'll have get support from Mixpanel themselves.

I don't think it's related but this library is a few versions behind due to Xcode complications I have not looked into fixing yet.

**Comment by Lelelo1** [comment]
The app has been live for 6 months, so I don't think i'ts related to the iOS version - 14.5 being from april this year.
Thanks for this tracking setting info, I was not aware of it, nor the networking blocking. I noticed when downloading the app from app store on my iPhone with `14.4.2` that there is no requesting tracking triggered by the app, having *Allow Apps to Request to Track* enabled (default).

I don't see connection between tracking and analytics though.

But I will talk with support at Mixpanel

**Comment by Lelelo1** [comment]
I updated to `14.6` and did not get any dialog, and the events are sent for me (in Europe) still

**Comment by beeradmoore** [comment]
Very curious. Would you be able to ping this thread when you have a solution?

**Comment by Lelelo1** [comment]
> Very curious. Would you be able to ping this thread when you have a solution?

Sure!

**Comment by Lelelo1** [comment]
So the response I got from support was to try to and reproduce it with vpn. And I also got the suggestion to set up a proxy for the app to use, and from it send there towards mixpanel.
But I will enable app analytics in AppCenter which I am already using for reporting crashes, to see if there is a difference with Mixpanel

**Comment by beeradmoore** [comment]
Interesting behaviour. Glad they gave you some ideas of what to do though.

**Comment by Lelelo1** [comment]
So I think I might have found the cause of the issue. It will take sometime before I can confirm though.

In the Mixpanel [docs](https://help.mixpanel.com/hc/en-us/articles/115004601543-Mobile-Customize-Flush-Interval) I read about `flushInterval`. And it should mean that anyone spending less the default of `60` seconds in the app does not report any events.

I read I need to call `flush` to send the events when application terminates. Do know you if I can:

```
// Main.cs in the iOS project
try {
    UIApplication.Main(args, null, "AppDelegate");
}
catch(Exception exc)
{
    call flush in any crash or app exit
}

```
.. should be enough, and cover all exiting/crashing?

**Comment by beeradmoore** [comment]
I don't think you can catch around that and flush. If users are backgrounding your app your analytics should flush. If your app is crashing I don't think you can force a flush. The closest thing I can see is in [applicationWillTerminate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate). But I think that is for  when your app is killed by the OS, not when crashing.

If you really need the data and users are force quitting or app is crashing then you are better off calling flush manually after you track some data.

**Comment by Lelelo1** [comment]
I don't think this can be it then, because of the flushing when in background being default. As I understand it the backgrounding always happens first, before an exit (when not crashing).
The app should be stable, and it is tested in a variety of devices in the field, also the App Center Crashes don't report crashes.
There is one side track I have investigated, which is this iTunes downloading. The app is only for iPhone but App Store Connect is reporting 50% desktop app units. I found out that these are pre macOS Big Sur and Windows + iPhone downloaders. If there is some trouble there it can account for some of the users not showing up in Mixpanel, which is around 80-85% 
Thanks for your help, I will continue to investigate and I will still try out the manual flushing after each `Track` call made.

**Comment by Lelelo1** [comment]
I setup Apples's CloudKit database and started to send user events to it a month ago. Looking at it know it reports the exact same events and users as Mixpanel has.
So: **There is nothing wrong in Mixpanel nor in the bindings**

The cause seems to be an unexpected user install behaviour. And there can also be some risk of silent crashes I guess.
