### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by Lelelo1** [beeradmoore/Xam.Plugin.Mixpanel.iOS#8]
**Crash reporting**

Maybe I have should turn to Mixpanel forum as well but I start here.
Im wondering how Mixpanel's crash reporting works. Im using AppCenter where many crashes are not shown but are reported by Mixpanel.

How are you handing Mixpanel crash reporting? And is there is some way I can use the bindings to throw exception so they end up in AppCenter?

**Comment by beeradmoore** [comment]
I don't use it personally as I use AppCenter for crashes and MixPanel for analytics.

According to their docs it should be [automatically recorded](https://developer.mixpanel.com/docs/ios#automatically-track-events). It could be possible that if you have AppCenter active then MixPanel isn't tracking the crashes.

**Comment by Lelelo1** [comment]
Yeah I also use AppCenter for crashes. It's just that I get concerned when Mixpanel reports crashes like shown below:

![Screenshot 2022-06-30 at 13 58 06](https://user-images.githubusercontent.com/42244983/176671824-fa9a69be-e179-4319-93f5-0eae06cca00c.png)

And AppCenter seem to function but don't report that crashing.

**Comment by beeradmoore** [comment]
That sounds like a bug for the AppCenter team.

**Comment by Lelelo1** [comment]
I’ll take it up with them and report back if I find anything
